In [ ]:
import pandas as pd

cars = pd.read_csv("cars_dailyRoutes.csv")
ai4i = pd.read_csv("ai4i2020.csv")

print(cars.columns)
print(ai4i.columns)

Index(['TIMESTAMP', 'MARK', 'MODEL', 'CAR_YEAR', 'ENGINE_POWER', 'AUTOMATIC',
       'VEHICLE_ID', 'BAROMETRIC_PRESSURE(KPA)', 'ENGINE_COOLANT_TEMP',
       'FUEL_LEVEL', 'ENGINE_LOAD', 'AMBIENT_AIR_TEMP', 'ENGINE_RPM',
       'INTAKE_MANIFOLD_PRESSURE', 'MAF', 'LONG TERM FUEL TRIM BANK 2',
       'FUEL_TYPE', 'AIR_INTAKE_TEMP', 'FUEL_PRESSURE', 'SPEED',
       'SHORT TERM FUEL TRIM BANK 2', 'SHORT TERM FUEL TRIM BANK 1',
       'ENGINE_RUNTIME', 'THROTTLE_POS', 'DTC_NUMBER', 'TROUBLE_CODES',
       'TIMING_ADVANCE', 'EQUIV_RATIO', 'MIN', 'HOURS', 'DAYS_OF_WEEK',
       'MONTHS', 'YEAR'],
      dtype='object')
Index(['UDI', 'Product ID', 'Type', 'Air temperature [K]',
       'Process temperature [K]', 'Rotational speed [rpm]', 'Torque [Nm]',
       'Tool wear [min]', 'Machine failure', 'TWF', 'HDF', 'PWF', 'OSF',
       'RNF'],
      dtype='object')

/tmp/ipykernel_13272/318659722.py:3: DtypeWarning: Columns (1,2,4,5,6,9,10,14,15,16,20,21,22,23,24,25,26,27) have mixed types. Specify dtype option on import or set low_memory=False.
  cars = pd.read_csv("cars_dailyRoutes.csv")

In [ ]:
opel = pd.read_csv(
    "opel_corsa_01.csv",
    sep=';',
    low_memory=False
)

In [ ]:
print("Cars Dataset")
print(cars.columns)

print("\nAI4I Dataset")
print(ai4i.columns)

print("\nOpel Dataset")
print(opel.columns)

Cars Dataset
Index(['TIMESTAMP', 'MARK', 'MODEL', 'CAR_YEAR', 'ENGINE_POWER', 'AUTOMATIC',
       'VEHICLE_ID', 'BAROMETRIC_PRESSURE(KPA)', 'ENGINE_COOLANT_TEMP',
       'FUEL_LEVEL', 'ENGINE_LOAD', 'AMBIENT_AIR_TEMP', 'ENGINE_RPM',
       'INTAKE_MANIFOLD_PRESSURE', 'MAF', 'LONG TERM FUEL TRIM BANK 2',
       'FUEL_TYPE', 'AIR_INTAKE_TEMP', 'FUEL_PRESSURE', 'SPEED',
       'SHORT TERM FUEL TRIM BANK 2', 'SHORT TERM FUEL TRIM BANK 1',
       'ENGINE_RUNTIME', 'THROTTLE_POS', 'DTC_NUMBER', 'TROUBLE_CODES',
       'TIMING_ADVANCE', 'EQUIV_RATIO', 'MIN', 'HOURS', 'DAYS_OF_WEEK',
       'MONTHS', 'YEAR'],
      dtype='object')

AI4I Dataset
Index(['UDI', 'Product ID', 'Type', 'Air temperature [K]',
       'Process temperature [K]', 'Rotational speed [rpm]', 'Torque [Nm]',
       'Tool wear [min]', 'Machine failure', 'TWF', 'HDF', 'PWF', 'OSF',
       'RNF'],
      dtype='object')

Opel Dataset
Index(['AltitudeVariation', 'VehicleSpeedInstantaneous', 'VehicleSpeedAverage',
       'VehicleSpeedVariance', 'VehicleSpeedVariation',
       'LongitudinalAcceleration', 'EngineLoad', 'EngineCoolantTemperature',
       'ManifoldAbsolutePressure', 'EngineRPM', 'MassAirFlow',
       'IntakeAirTemperature', 'VerticalAcceleration',
       'FuelConsumptionAverage', 'roadSurface', 'traffic', 'drivingStyle'],
      dtype='object')

In [ ]:
import pandas as pd
import numpy as np

cars = pd.read_csv("cars_dailyRoutes.csv", low_memory=False)
ai4i = pd.read_csv("ai4i2020.csv")
opel = pd.read_csv("opel_corsa_01.csv", sep=';')

In [ ]:
opel.isnull().sum()

AltitudeVariation             54
VehicleSpeedInstantaneous      7
VehicleSpeedAverage          354
VehicleSpeedVariance         354
VehicleSpeedVariation         34
LongitudinalAcceleration       0
EngineLoad                     0
EngineCoolantTemperature       0
ManifoldAbsolutePressure       0
EngineRPM                      0
MassAirFlow                    0
IntakeAirTemperature           0
VerticalAcceleration           0
FuelConsumptionAverage        97
roadSurface                    0
traffic                        0
drivingStyle                   0
dtype: int64

In [ ]:
opel.fillna(opel.median(numeric_only=True), inplace=True)

In [ ]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

opel['roadSurface'] = le.fit_transform(opel['roadSurface'])
opel['traffic'] = le.fit_transform(opel['traffic'])
opel['drivingStyle'] = le.fit_transform(opel['drivingStyle'])

In [ ]:
cols = [
    'roadSurface',
    'traffic',
    'VerticalAcceleration',
    'VehicleSpeedInstantaneous'
]

for c in cols:
    opel[c] = (
        opel[c]
        .astype(str)
        .str.replace(',', '.', regex=False)
    )

for c in cols:
    opel[c] = pd.to_numeric(
        opel[c],
        errors='coerce'
    )

opel[cols] = opel[cols].fillna(
    opel[cols].median()
)

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

opel[cols] = scaler.fit_transform(
    opel[cols]
)

In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

opel[cols] = scaler.fit_transform(
    opel[cols]
)

In [ ]:
opel[cols].dtypes

roadSurface                  float64
traffic                      float64
VerticalAcceleration         float64
VehicleSpeedInstantaneous    float64
dtype: object

In [ ]:
print(opel['roadSurface'].unique())
print(opel['traffic'].unique())

[0. 1.]
[0.5 1.  0. ]

In [ ]:
opel['IRSI'] = (
      0.35 * opel['roadSurface']
    + 0.30 * opel['traffic']
    + 0.20 * abs(opel['VerticalAcceleration'])
    + 0.15 * opel['VehicleSpeedInstantaneous']
) * 100

In [ ]:
opel[['IRSI']].head()

        IRSI
0  25.083062
1  25.019544
2  28.281668
3  28.281668
4  24.892508

In [ ]:
opel['IRSI'].describe()

count    7392.000000
mean       30.034582
std         8.851702
min         4.834691
25%        25.560261
50%        29.744889
75%        34.145896
max        72.231306
Name: IRSI, dtype: float64

In [ ]:
opel['LongitudinalAcceleration'].dtype
opel['drivingStyle'].dtype

dtype('int64')

In [ ]:
opel['LongitudinalAcceleration'].dtype

dtype('O')

In [ ]:
opel['LongitudinalAcceleration'] = (
    opel['LongitudinalAcceleration']
    .astype(str)
    .str.replace(',', '.', regex=False)
)

opel['LongitudinalAcceleration'] = pd.to_numeric(
    opel['LongitudinalAcceleration'],
    errors='coerce'
)

In [ ]:
opel['LongitudinalAcceleration'].fillna(
    opel['LongitudinalAcceleration'].median(),
    inplace=True
)

/tmp/ipykernel_13272/4141322452.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  opel['LongitudinalAcceleration'].fillna(

In [ ]:
opel['drivingStyle'].fillna(
    opel['drivingStyle'].mode()[0],
    inplace=True
)

/tmp/ipykernel_13272/3151215979.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  opel['drivingStyle'].fillna(

In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

opel[['LongitudinalAcceleration','drivingStyle']] = (
    scaler.fit_transform(
        opel[['LongitudinalAcceleration','drivingStyle']]
    )
)

In [ ]:
opel['DrivingAggressiveness'] = (
      0.4 * opel['VehicleSpeedInstantaneous']
    + 0.4 * abs(opel['LongitudinalAcceleration'])
    + 0.2 * opel['drivingStyle']
) * 100

In [ ]:
opel[['DrivingAggressiveness']].head()

   DrivingAggressiveness
0              40.216034
1              40.216034
2              49.267836
3              49.367414
4              40.480169

In [ ]:
opel['DrivingAggressiveness'].describe()

count    7392.000000
mean       48.879281
std        14.902049
min        15.766245
25%        39.854008
50%        48.289283
75%        56.583479
max        87.885568
Name: DrivingAggressiveness, dtype: float64

In [ ]:
opel['FuelConsumptionAverage'].dtype
opel['VehicleSpeedAverage'].dtype

dtype('O')

In [ ]:
for c in ['FuelConsumptionAverage', 'VehicleSpeedAverage']:
    opel[c] = (
        opel[c]
        .astype(str)
        .str.replace(',', '.', regex=False)
    )

    opel[c] = pd.to_numeric(
        opel[c],
        errors='coerce'
    )

In [ ]:
opel['FuelConsumptionAverage'].fillna(
    opel['FuelConsumptionAverage'].median(),
    inplace=True
)

opel['VehicleSpeedAverage'].fillna(
    opel['VehicleSpeedAverage'].median(),
    inplace=True
)

/tmp/ipykernel_13272/485848022.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  opel['FuelConsumptionAverage'].fillna(
/tmp/ipykernel_13272/485848022.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  opel['VehicleSpeedAverage'].fillna(

In [ ]:
opel['FuelEfficiencyScore'] = (
    opel['VehicleSpeedAverage']
    /
    (opel['FuelConsumptionAverage'] + 1)
)

In [ ]:
opel[['FuelEfficiencyScore']].head()

   FuelEfficiencyScore
0             1.728161
1             1.728161
2             1.728161
3             1.728161
4             1.728161

In [ ]:
def road_category(x):
    if x < 30:
        return 'Good'
    elif x < 60:
        return 'Moderate'
    else:
        return 'Bad'

opel['RoadCategory'] = opel['IRSI'].apply(road_category)

In [ ]:
opel[['IRSI', 'RoadCategory']].head()

        IRSI RoadCategory
0  25.083062         Good
1  25.019544         Good
2  28.281668         Good
3  28.281668         Good
4  24.892508         Good

In [ ]:
cars[
[
'ENGINE_LOAD',
'ENGINE_RPM',
'ENGINE_COOLANT_TEMP'
]
].head()

  ENGINE_LOAD  ENGINE_RPM  ENGINE_COOLANT_TEMP
0      33,30%      1009.0                 80.0
1      32,50%      1003.0                 80.0
2      32,90%       995.0                 80.0
3      32,50%      1004.0                 80.0
4      32,90%      1005.0                 80.0

In [ ]:
cols = [
    'ENGINE_LOAD',
    'ENGINE_RPM',
    'ENGINE_COOLANT_TEMP'
]

for c in cols:
    cars[c] = pd.to_numeric(
        cars[c],
        errors='coerce'
    )

cars[cols] = cars[cols].fillna(
    cars[cols].median()
)

In [ ]:
cols = [
    'ENGINE_LOAD',
    'ENGINE_RPM',
    'ENGINE_COOLANT_TEMP'
]

for c in cols:
    cars[c] = pd.to_numeric(
        cars[c],
        errors='coerce'
    )

cars[cols] = cars[cols].fillna(
    cars[cols].median()
)

In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

cars[cols] = scaler.fit_transform(
    cars[cols]
)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/_array_api.py:776: RuntimeWarning: All-NaN slice encountered
  return xp.asarray(numpy.nanmin(X, axis=axis))
/usr/local/lib/python3.12/dist-packages/sklearn/utils/_array_api.py:793: RuntimeWarning: All-NaN slice encountered
  return xp.asarray(numpy.nanmax(X, axis=axis))

In [59]:
opel.to_csv(
    'driving_behavior_featured.csv',
    index=False
)

In [ ]:
cars['ENGINE_LOAD'].isnull().sum()

np.int64(60439)

In [ ]:
cars['ENGINE_LOAD'].unique()[:20]

array([nan])

In [ ]:
cols = ['ENGINE_LOAD','ENGINE_RPM','SPEED']

for c in cols:
    cars[c] = (
        cars[c]
        .astype(str)
        .str.replace(',', '.')
    )

    cars[c] = pd.to_numeric(
        cars[c],
        errors='coerce'
    )

In [ ]:
cars[cols] = cars[cols].fillna(
    cars[cols].median()
)

In [ ]:
cars['VehicleStressIndex'] = (
      0.4 * cars['ENGINE_LOAD']
    + 0.4 * cars['ENGINE_RPM']
    + 0.2 * cars['SPEED']
)

In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

cars[['VehicleStressIndex']] = scaler.fit_transform(
    cars[['VehicleStressIndex']]
)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/_array_api.py:776: RuntimeWarning: All-NaN slice encountered
  return xp.asarray(numpy.nanmin(X, axis=axis))
/usr/local/lib/python3.12/dist-packages/sklearn/utils/_array_api.py:793: RuntimeWarning: All-NaN slice encountered
  return xp.asarray(numpy.nanmax(X, axis=axis))

In [ ]:
cars = pd.read_csv('cars_dailyRoutes.csv')

/tmp/ipykernel_13272/2136115748.py:1: DtypeWarning: Columns (1,2,4,5,6,9,10,14,15,16,20,21,22,23,24,25,26,27) have mixed types. Specify dtype option on import or set low_memory=False.
  cars = pd.read_csv('cars_dailyRoutes.csv')

In [ ]:
cars['ENGINE_LOAD'].head(20)

0     33,30%
1     32,50%
2     32,90%
3     32,50%
4     32,90%
5     32,90%
6     33,30%
7     33,30%
8     33,30%
9     32,90%
10    34,50%
11    34,50%
12    34,10%
13    34,90%
14    34,90%
15    37,30%
16    26,70%
17    36,90%
18    29,40%
19    36,50%
Name: ENGINE_LOAD, dtype: object

In [ ]:
cars['ENGINE_LOAD'].unique()[:20]

array(['33,30%', '32,50%', '32,90%', '34,50%', '34,10%', '34,90%',
       '37,30%', '26,70%', '36,90%', '29,40%', '36,50%', '31,00%',
       '32,20%', '30,20%', '29,00%', '29,80%', '31,40%', '30,60%',
       '25,50%', '27,10%'], dtype=object)

In [ ]:
cars['ENGINE_LOAD'] = (
    cars['ENGINE_LOAD']
    .str.replace('%', '', regex=False)
    .str.replace(',', '.', regex=False)
    .astype(float)
)

In [ ]:
cars['ENGINE_LOAD'].head()

0    33.3
1    32.5
2    32.9
3    32.5
4    32.9
Name: ENGINE_LOAD, dtype: float64

In [ ]:
cars['VehicleStressIndex'] = (
      0.4 * cars['ENGINE_LOAD']
    + 0.4 * cars['ENGINE_RPM']
    + 0.2 * cars['SPEED']
)

In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

cars[['VehicleStressIndex']] = scaler.fit_transform(
    cars[['VehicleStressIndex']]
)

In [ ]:
cars[['VehicleStressIndex']].head()

   VehicleStressIndex
0            0.169420
1            0.167418
2            0.165179
3            0.167712
4            0.168124

In [60]:
cars.to_csv(
    'cars_featured.csv',
    index=False
)